### ISSUE TITLE
Enable SBAS for UBlox

### ISSUE THREAD

**Issue by jgoppert** [PX4/GpsDrivers#2]
Looking at the code it looks like UBX_CONFIGURE_SBAS is not defined, so it seems for the ublox sbas is disabled. What is the reasoning behind this?

https://github.com/PX4/GpsDrivers/blob/master/src/ubx.cpp#L221

**Comment by LorenzMeier** [comment]
Flaky performance in some reasons of the world, e.g. Australia.
