### ISSUE TITLE
where can I find the implementation of gps_absolute_time() ?

### ISSUE THREAD

**Issue by abhishekkumar1902** [PX4/GpsDrivers#41]
Where can I find the implementation of the function `gps_absolute_time()` used in ubx.cpp?

**Comment by bkueng** [comment]
You have to implement it yourself if you want to use the drivers in your project. It's a method that returns a timestamp in microsecond accuracy.
See for example QGC: https://github.com/mavlink/qgroundcontrol/blob/master/src/GPS/definitions.h#L79.

**Comment by abhishekkumar1902** [comment]
Thanks!
