### ISSUE TITLE
UBX with u-blox neo-m9n does not work

### ISSUE THREAD

**Issue by cyrili** [PX4/GpsDrivers#50]
I have [this ](https://www.gnss.store/gnss-gps-modules/118-ublox-mini-neo-m8n-gps-gnss-lis3mdl-compass-triple-band-ant.html) GNSS receiver witch uses the new u-blox neo-m9n module.

it appears that this module got rid of a couple of configuration items that are written to by px4's gps driver:

UBX_CFG_KEY_CFG_UART1OUTPROT_RTCM3X
UBX_CFG_KEY_CFG_USBOUTPROT_RTCM3X
UBX_CFG_KEY_NAVHPG_DGNSSMODE

writing to these causes a NAK message to come back and the gnss module to be misidentified as protocol_version<27 by the gps driver. 

deleting the relevant lines of code makes my module work flawlessly, but I'm not sure if that breaks compatibility with some older model.

**Comment by LorenzMeier** [comment]
Thanks for reporting! I've ordered the module for @bkueng so that we can cross-test.

**Comment by bkueng** [comment]
Thanks @cyrili, I finally got the hardware and fixed it in https://github.com/PX4/GpsDrivers/pull/55.
