### ISSUE TITLE
Conversion from  degrees, minutes and seconds to degrees * 1e7 

### ISSUE THREAD

**Issue by djmira92** [PX4/GpsDrivers#6]
In https://github.com/PX4/GpsDrivers/blob/master/src/ashtech.cpp#L230
the conversion from  degrees, minutes and seconds to degrees * 1e7 is right?

Consulting this https://www.uwgb.edu/dutchs/UsefulData/UTMFormulas.HTM

the formula should be dd.ff = dd + mm/60 + ss/3600

In the code is only used dd.ff = dd + mm/60

**Comment by bkueng** [comment]
Thanks for the hint, but yes it's correct. NMEA gives longitude as DDDMM.MMMMM, no seconds.
see http://gpsworld.com/what-exactly-is-gps-nmea-data/
