### ISSUE TITLE
Position and velocity Hz ashtech

### ISSUE THREAD

**Issue by djmira92** [PX4/GpsDrivers#7]
I am using the astech driver to another gnss that uses the nmea protocol.
When consulting the gps status in nsh the velocity frequency is 0.
In code, comparing  to ublox driver i saw that is missing a _rate_count_vel++. Was that on purpose?

Another issue is that the position frequency is multiplied by 2. I think that is because of the gga and pos message. Is possible that they give differente position coordinates and because that the frequency is double?

**Comment by bkueng** [comment]
No, you're right, the velocity rate seems to had been missing. Can you test #8?

> Another issue is that the position frequency is multiplied by 2.

What do you mean exactly?

**Comment by djmira92** [comment]
That seems to solve the problem.

Well, i have the gnns running at 5Hz and in nsh shows that is at 10Hz. And it's because of  _rate_count_lat_lon++; in GGA and POS messages.

**Comment by bkueng** [comment]
I see. Do the GGA & POS provide the same position? If so, from what I see POS provides all the information that GGA does plus more. We can then simply ignore GGA if we receive both messages. Can you test this? I don't have an ashtech gps.

**Comment by djmira92** [comment]
Well, like i said, i don't have a ashtech gps. i have other gps that uses the same nmea protocol.

I tested it, and they have the same position coordinates.

**Comment by bkueng** [comment]
I extended the driver, can you test #9?

**Comment by djmira92** [comment]
That worked! 

Thanks for your work.
